Repository sotoblanco/discord-chat-bot, pull requests merged in 2025-07, with the labels that each got.

#10 Feature/uv support
  .gitignore
  README.md
  interactive_qa.py
  pyproject.toml
Labels: Review effort 2/5

#12 Improve robustness of import statement
  interactive_qa.py
Labels: Review effort 1/5

#13 MCP server
  README.md
  pyproject.toml
  src/modal_mcp_server.py
  src/vector_emb.py
  test_mcp_server.py
Labels: Review effort 3/5
